version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017 Preview
before_build:
- cmd: dotnet restore source/App/Web/Solution.App.Web.csproj
build:
  project: source/App/Web/Solution.App.Web.csproj
  verbosity: minimal
